### ISSUE TITLE
我发现个问题

### ISSUE THREAD

**Issue by Coolzhou** [YueRuo/YRSideViewController#2]
rootViewController 如果带导航栏，侧滑，有的时候，发现发生app的状态栏不见了，然后导航栏会向上移动，导航栏和视图之间就会产生20 的间距。不知道，这样描述，是否明白！

**Comment by gingingin** [comment]
是否有修改状态栏的代码出现

**Comment by YueRuo** [comment]
@Mirzhou 此控件是基于vc的frame修改做的调整，控件本身对状态栏不会有调整，请检查是否有状态栏样式的改动或者修改
